### ISSUE TITLE
Does it run on your phone?

### ISSUE THREAD

**Issue by zeroche72** [Android-for-Python/c4k_opencv_example#3]
Thanks for providing good information.

I compiled the code with Google Colab.
The apk file was created successfully.

But it didn't work on my phone.

So i wish i have the apk file you made.
I want to find out what I did wrong.

Please help.

**Comment by zeroche72** [comment]
I had success both compiling and running on the phone.
When compiling with Colab, the mod folder and files had to be together.

Thank you for providing information.

**Comment by RobertFlatt** [comment]
This is not about api 33

Key Point: There is an issue related to certain versions of KivyMD that shows up only on certain Android devices.

The two tests you did were the before (the issue) and after (the issue) versions of KivyMD. Its a little more complex because of Kivy changes.

So that is why those tests worked.

Next question why did your previous tests (api 32) work? 

The absolute answer is I don't know because I don't know anything about the tests you did.
But if it is like everybody else, either you used an earlier version of KivyMD  ( <= 1.0.2), or tested an Android device that doesn't exhibit the issue.

Finally what is the Android issue? It is related to the device software implementation for the GPU and OpenGL compliance. I don't know what devices have the issue.

Oh, and I know nothing about Colab, never used it.
