### ISSUE TITLE
Android Apk Not working

### ISSUE THREAD

**Issue by kXborg** [Android-for-Python/c4k_opencv_example#4]
Built the android app with the default settings. 

The app opens successfully, and icons (buttons) are displayed. 

However, the camera is not working. While switching the camera, the screen turns blank white. Please help.

**Comment by kXborg** [comment]
@Android-for-Python ,

This is the build log. I can observe two things.
1. supported SDK warning.
2. Unable to strip the following libraries.

The build however completed. The build log (few final lines) is,
```
[INFO]:    Hook: ignore after_apk_build
[INFO]:    Hook: ignore before_apk_assemble
[INFO]:    Detected highest available build tools version to be 34.0.0-rc1
[DEBUG]:   -> running gradlew clean assembleDebug
[DEBUG]:        Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
[DEBUG]:   
[DEBUG]:        > Configure project :
[DEBUG]:        WARNING:Using flatDir should be avoided because it doesn't support any meta-data formats.
[DEBUG]:        WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33       > IDLE
[DEBUG]:   
[DEBUG]:        This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
[DEBUG]:   
[DEBUG]:        This warning can be suppressed by adding
[DEBUG]:            android.suppressUnsupportedCompileSdk=33
[DEBUG]:        to this project's gradle.properties
[DEBUG]:   
[DEBUG]:        The build will continue, but you are strongly encouraged to update your project to
[DEBUG]:        use a newer Android Gradle Plugin that has been tested with compileSdk = 33

[DEBUG]:   ebugR> Task :stripDebugDebugSymbols                                        [DEBUG]:   ugDebUnable to strip the following libraries, packaging them as they are: libSDL2.so, libSDL2_image.so, libSDL2_mixer.so, libSDL2_ttf.so, libcrypto1.1.so, libffi.so, libimage_processing_util_jni.so, libmain.so, libopencv_calib3d.so, libopencv_core.so, libopencv_dnn.so, libopencv_features2d.so, libopencv_flann.so, libopencv_gapi.so, libopencv_highgui.so, libopencv_imgcodecs.so, libopencv_imgproc.so, libopencv_ml.so, libopencv_objdetect.so, libopencv_photo.so, libopencv_stitching.so, libopencv_video.so, libopencv_videoio.so, libpybundle.so, libpython3.9.so, libsqlite3.so, libssl1.1.so.
[DEBUG]:   
[DEBUG]:        > Task :compileDebugJavaWithJavac
[DEBUG]:        Note: Some input files use or override a deprecated API.
[DEBUG]:        Note: Recompile with -Xlint:deprecation for details.
[DEBUG]:   
[DEBUG]:        Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.E
[DEBUG]:   
[DEBUG]:        You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[DEBUG]:   
[DEBUG]:        See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings
[DEBUG]:   
[DEBUG]:        BUILD SUCCESSFUL in 12s
[DEBUG]:        31 actionable tasks: 30 executed, 1 up-to-date

[INFO]:    <- directory context /home/kukil/Desktop/Android/27Feb/c4k_opencv_example/.buildozer/android/platform/python-for-android
[INFO]:    Of the existing distributions, the following meet the given requirements:
[INFO]:         newday: min API 21, includes recipes (hostpython3, libffi, openssl, sdl2_image, sdl2_mixer, sdl2_ttf, sqlite3, python3, sdl2, setuptools, cython, six, numpy, pyjnius, android, kivy, opencv, certifi, gestures4kivy, camera4kivy), built for archs (arm64-v8a)
[INFO]:    newday has compatible recipes, using this one
[INFO]:    Hook: ignore after_apk_assemble
[INFO]:    # Copying android package to current directory
[INFO]:    # Android package filename not found in build output. Guessing...
[INFO]:    # Found android package file: /home/kukil/Desktop/Android/27Feb/c4k_opencv_example/.buildozer/android/platform/build-arm64-v8a/dists/newday/build/outputs/apk/debug/newday-debug.apk
[INFO]:    # Add version number to android package
[INFO]:    # Android package renamed to newday-debug-0.1.apk
[DEBUG]:   -> running cp /home/kukil/Desktop/Android/27Feb/c4k_opencv_example/.buildozer/android/platform/build-arm64-v8a/dists/newday/build/outputs/apk/debug/newday-debug.apk newday-debug-0.1.apk
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
```

**Comment by Android-for-Python** [comment]
Builds and runs here, I can't replicate.

I don't see anything significant in the build log, but what I wanted was the run time logcat containing an error message.

Two debugging suggestions:
- Check your physical environment has sufficient light to detect edges.
- Try building one of the other examples, it doesn't matter which one just want to see if the camera works.

**Comment by kXborg** [comment]
Here is the logcat output after opening the app. I named it `Camera App`. I am not sure if it's the correct way to share logcat output. I have copied the log from about the middle of the terminal. Hope it covers what you asked.

[logcat.txt](https://github.com/Android-for-Python/c4k_opencv_example/files/10837372/logcat.txt)

**Comment by kXborg** [comment]
> Builds and runs here, I can't replicate.
> 
> I don't see anything significant in the build log, but what I wanted was the run time logcat containing an error message.
> 
> Two debugging suggestions:
> 
> * Check your physical environment has sufficient light to detect edges.
> * Try building one of the other examples, it doesn't matter which one just want to see if the camera works.

I have tried building c4k_photo_example as well. Builds successfully. However, the app shows red, brown, pink backgrounds with functioning buttons only. Camera feed does not connect.

**Comment by Android-for-Python** [comment]
Are you the same person as OpenCV_kukil on Discord? If so lets have our discussion in one place, two discussions are confusing to me.

I didn't see anything I recognized as an issue in the logcat. But those internal Android messages vary a lot, so it is somewhat guesswork. There are messages about video recording which make no sense in the context of the OCV example. Its really important that we know we are taking about the same thing, a modified example was unhelpful.

The basic photo example is more interesting, but not optimistic. It looks like you are seeing the camera image, but mis-configured. The OCV example replaces the image with a black screen and edges in the image as white lines, so we loose any info about actual camera behavior. You can see something that might be misconfiguration in the logcat (from your apps process, but the actual messages are from inside Android code):
```
2023-02-27 13:29:10.114 21139-21677 ExtendedACodec          org.example.newday                   I  setupVideoEncoder()
2023-02-27 13:29:10.114 21139-21677 OMXUtils                org.example.newday                   W  do not know color format 0x7fa30c06 = 2141391878
```

C4k uses whatever default is specified by CameraX (the Android camera api is called CameraX). Your device is supported by the camerax api https://developer.android.com/training/camerax/devices so its hard to know what to suggest. I would certainly wonder about the configuration in this case. But since I cant replicate on a Pixel and can't test a camera on an emulator, I can't investigate.

So two blind guess experiments:

1) Lets see if the CameraX defaults from before your device was supported work: 

C4k uses the latest release camerax api version, this is specified in `c4k_photo_example/camerax_provider/gradle_options.py` like this https://github.com/Android-for-Python/camerax_provider/blob/0.0.3/gradle_options.py#L27-L31

Lets try an older version of the Android package. Edit `c4k_photo_example/camerax_provider/gradle_options.py` to this https://github.com/Android-for-Python/camerax_provider/blob/0.0.2/gradle_options.py#L27-L31 

Then `buildozer appclean` and build again.

2) Disable video recording

Add `enable_video = False` the to the connect_camera method like this `connect_camera(enable_video = False, ...other options..).`
https://github.com/Android-for-Python/Camera4Kivy#behavior-android-no-supported-surface-combination

Then `buildozer appclean` and build again.

**Comment by Android-for-Python** [comment]
Looking for some feedback.
Did either of those address the issue?
If so which one?
Thanks.
